---
- name: test if certbot_system is set correctly
  assert:
    that:
      - certbot_system is defined
      - certbot_system in [ "apache", "nginx", "haproxy" ]
    quiet: yes

- name: test if certbot_domains is set correctly
  assert:
    that:
      - certbot_domains is defined
      - certbot_domains is iterable
    quiet: yes

- name: test if item in certbot_domains is set correctly
  assert:
    that:
      - item is defined
      - '"." in item'
    quiet: yes
  loop: "{{ certbot_domains }}"

- name: test if certbot_email is set correctly
  assert:
    that:
      - certbot_email is defined
    quiet: yes
